### ISSUE TITLE
Error when starting project which with provider and consumer in the same project

### ISSUE THREAD

**Issue by luffyke** [dubbo/dubbo-spring-boot-project#51]
As the title, error log shows as below:
```
Caused by: java.lang.IllegalStateException: Failed to check the status of the service my.service.ActivityService. No provider available for the service my.service.ActivityService from the url zookeeper://localhost:2181/com.alibaba.dubbo.registry.RegistryService?application=my-dubbo&dubbo=2.0.1&interface=my.service.ActivityService&methods=sayHello&pid=37318&register.ip=myip&side=consumer&timestamp=1520507541192 to the consumer myip use dubbo version 2.0.1
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:422)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:65)
```

dubbo config
```
dubbo.scan.base-packages=my.service
dubbo.application.id=my-dubbo
dubbo.application.name=my-dubbo
dubbo.protocol.id=dubbo
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.registry.id=my-registry
dubbo.registry.address=zookeeper://localhost:2181
dubbo.registry.client=curator
```

**Comment by luffyke** [comment]
Seems the reason is consumer is inited in front of provider, after set
```
@Reference(check = false)
```
and the program is as expected now.

**Comment by luffyke** [comment]
Another question.
when provider and consumer are in the same project, how to ensure provider is inited before consumer?

**Comment by luffyke** [comment]
And dubbo use zkclient as default client of zk, but the dependency in dbbo-spring-boot-starter is 
```
<dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
        </dependency>
```
Suggest changing document(README) to give tips by setting below code to user:
```
dubbo.registry.client=curator
```

**Comment by mercyblitz** [comment]
@luffyke Are there some service both  `@Service` or `@Reference` on same project, If yes, @Reference field can't reference no ready `@Service`

**Comment by luffyke** [comment]
@mercyblitz Yes, In same project, make sense with your answer.
Any suggestion for this situation?
set ```check = false``` or ```lazy = true``` for Reference?

**Comment by luffyke** [comment]
Finally i use ```dubbo.consumer.check=false``` for this issue.
